config/routes.rb
Fpl::Application.routes.draw do
  match 'howto' => 'players#howto'
  resources :players do
    collection do
      get :filter
    end
  end

  root :to => 'players#filter'

end

app/models/player.rb
class Player < ActiveRecord::Base
  def now_cost_float
    self.now_cost.to_f / 10
  end
  
  #http://stackoverflow.com/a/6892207/1415352
  def as_json(options = { })
    h = super(options)
    h[:now_cost_float] = self.now_cost_float
    h
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.json
  def index
    @players = Player.where("status != 'u'")
    
    jsondata = {}
    jsondata['total'] = "50"
    jsondata['page'] = "1"
    jsondata['records'] = @players.count.to_s
    jsondata['rows'] = @players
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: jsondata }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end
  
  def filter    
    respond_to do |format|
      format.html 
    end
  end

  def howto
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:error, :info, :success, :warning]

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?
      
      type = :success if type == :notice
      type = :error   if type == :alert
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                           msg.html_safe, :class => "alert fade in alert-#{type}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= favicon_link_tag 'favicon.ico' %>
    <title><%= content_for?(:title) ? yield(:title) : "FPL Assistant" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= yield :css %>
    
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">FPL Assistant</a>
          <div class="container nav-collapse">
            <ul class="nav">
                <li><%= link_to "Home", :controller => :players, :action => :filter %>
                <li><%= link_to "How to", :controller => :players, :action => :howto %>
                <li><%= link_to "Changelog", "changelog.txt" %>
                <li><%= link_to "keithxm23", "http://www.keithxm23.com"  %></li>
                <li>
                  <a id="bookmarkme" href="#" rel="sidebar" title="bookmark this page">Bookmark This Page</a>
                </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      
      <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->


      <footer>
        <br/><br/>
        <p>Disclaimer: I do not claim ownership for any of this data. The data is entirely the property of http://fantasy.premierleague.com/
        <br/>
        <p>
        Feel free to drop me an email at keithxm23 (at) gmail (dot) com if you're looking for help or if you have any suggestions. Cheers!
        </p>
        <center>COYG !!! <%=image_tag("arsenal_icon.png")%></center>
        <br/>
        <!-- hitwebcounter Code START -->
        <a href="http://www.hitwebcounter.com/" target="_blank">
          <img src="http://hitwebcounter.com/counter/counter.php?page=5765026&style=0007&nbdigits=6&type=ip&initCount=0" title="joomla and drupal websites counter" Alt="joomla and drupal websites counter"   border="0" >
        </a><br/>
        <!-- hitwebcounter.com --><a href="http://www.hitwebcounter.com/"  
          target="_blank" style="font-family: Geneva, Arial, Helvetica, sans-serif; 
          font-size: 10px; color: #63766C; text-decoration: none ;">
        </a>   
          
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :js %>
    <script type="text/javascript">
        $(function() {
            $('#bookmarkme').click(function() {
                if (window.sidebar && window.sidebar.addPanel) { // Mozilla Firefox Bookmark
                    window.sidebar.addPanel(document.title,window.location.href,'');
                } else if(window.external && ('AddFavorite' in window.external)) { // IE Favorite
                    window.external.AddFavorite(location.href,document.title); 
                } else if(window.opera && window.print) { // Opera Hotlist
                    this.title=document.title;
                    return true;
                } else { // webkit - safari/chrome
                    alert('Press ' + (navigator.userAgent.toLowerCase().indexOf('mac') != - 1 ? 'Command/Cmd' : 'CTRL') + ' + D to bookmark this page.');
                }
            });
        });
    </script>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
              })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-38355235-3', 'auto');
        ga('require', 'displayfeatures');
        ga('require', 'linkid', 'linkid.js');
        ga('send', 'pageview');

    </script>

  </body>
</html>

app/views/players/_form.html.erb
<%= form_for @player, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :elementid, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :elementid, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :transfers_out, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :transfers_out, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :code, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :code, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :event_total, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :event_total, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_season_points, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :last_season_points, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :squad_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :squad_number, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :transfer_balance, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :transfer_balance, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :news_updated, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :news_updated, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :news_added, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :news_added, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :event_cost, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :event_cost, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :web_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :web_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :in_dreamteam, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :in_dreamteam, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :team_code, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :team_code, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :shirt_image_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :shirt_image_url, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :transfers_out_event, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :transfers_out_event, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :element_type_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :element_type_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :max_cost, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :max_cost, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :selected, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :selected, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :min_cost, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :min_cost, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :total_points, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :total_points, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :type_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :type_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :team_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :team_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :status, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :added, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :added, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :form, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :form, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :shirt_mobile_image_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :shirt_mobile_image_url, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :current_fixture, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :current_fixture, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :now_cost, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :now_cost, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :points_per_game, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :points_per_game, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :transfers_in, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :transfers_in, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :news, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :news, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :original_cost, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :original_cost, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :event_points, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :event_points, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :news_return, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :news_return, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :next_fixture, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :next_fixture, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :transfers_in_event, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :transfers_in_event, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :selected_by, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :selected_by, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :team_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :team_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :photo_mobile_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :photo_mobile_url, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                players_path, :class => 'btn' %>
  </div>
<% end %>

app/views/players/edit.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/players/howto.html.erb
<div id="howto">
  <h2>How to use this grid</h2>
  <p>
  The grid allows you to apply multiple filters to find the exact player you're looking for. This can be done multiple ways. From the 'Query' modal-box or directly from the filter-toolbar. Additionally, there are several columns/data-points on which queries can be made. You can choose to show/hide these columns based on the type of player you are looking for.
  </p>
  <h3>Main buttons</h3>
  <p>
  The 3 main buttons here are 1: Query - which takes you to the query-modal-box. 2: Reset, which resets all filters that you may have applied and 3. The show/hide columns button which lets you select the columns you would like to see.
  </p>
  <%= image_tag("buttons.png") %>

  <h3>Query</h3>
  <p>
  The Query modal box lets you specify multiple filters and conditions to fine tune your search. You can choose to find players that meet 'all' filters (logical-AND) or 'any' of the filters you specify (logical-OR).
  Additionally, for each of the filters you can choose the conditions that apply based on the data-type. For instance, numeric datatypes let you select, equals, not-equals, greater than and lesser than. And alphabetical fields let you perform word-matching queries.
  </p>
  <%= image_tag("query.png") %>

  <h3>Toolbar</h3>
  <p>
  The Filter-Toolbar lets you perform the same queries without without having to enter the 'Query' section. Simply set the filters at the top of the toolbar and hit enter.
  </p>
  <%= image_tag("toolbar.png") %>

  <h3>Show/Hide Columns</h3>
  <p>
  If you're looking for a goalkeeper, you may not be interested in Goals and Assists but may be looking for data-points like Clean Sheets and Penalties saved. You can select columns of your choice by hitting the 'Show/Hide columns button' and then selecting the columns you're interested in by checking/unchecking the respective checkboxes.
  </p>
  <%= image_tag("columns.png") %>

  <h3>Pagination</h3>
  <p>
  You can select how many results you would like to see on each page by using the drop down menu. Additionally you can jump forward and backward to any page you're looking for by using the controls here.
  </p>
  <%= image_tag("pagination.png") %> 
  <br/><br/>

</div>

app/views/players/index.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:second_name) %></th>
      <th><%= model_class.human_attribute_name(:elementid) %></th>
      <th><%= model_class.human_attribute_name(:transfers_out) %></th>
      <th><%= model_class.human_attribute_name(:code) %></th>
      <th><%= model_class.human_attribute_name(:event_total) %></th>
      <th><%= model_class.human_attribute_name(:last_season_points) %></th>
      <th><%= model_class.human_attribute_name(:squad_number) %></th>
      <th><%= model_class.human_attribute_name(:transfers_balance) %></th>
      <th><%= model_class.human_attribute_name(:news_updated) %></th>
      <th><%= model_class.human_attribute_name(:news_added) %></th>
      <th><%= model_class.human_attribute_name(:event_cost) %></th>
      <th><%= model_class.human_attribute_name(:web_name) %></th>
      <th><%= model_class.human_attribute_name(:in_dreamteam) %></th>
      <th><%= model_class.human_attribute_name(:team_code) %></th>
      <th><%= model_class.human_attribute_name(:shirt_image_url) %></th>
      <th><%= model_class.human_attribute_name(:transfers_out_event) %></th>
      <th><%= model_class.human_attribute_name(:element_type_id) %></th>
      <th><%= model_class.human_attribute_name(:max_cost) %></th>
      <th><%= model_class.human_attribute_name(:selected) %></th>
      <th><%= model_class.human_attribute_name(:min_cost) %></th>
      <th><%= model_class.human_attribute_name(:total_points) %></th>
      <th><%= model_class.human_attribute_name(:type_name) %></th>
      <th><%= model_class.human_attribute_name(:team_name) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:added) %></th>
      <th><%= model_class.human_attribute_name(:form) %></th>
      <th><%= model_class.human_attribute_name(:shirt_mobile_image_url) %></th>
      <th><%= model_class.human_attribute_name(:current_fixture) %></th>
      <th><%= model_class.human_attribute_name(:now_cost) %></th>
      <th><%= model_class.human_attribute_name(:points_per_game) %></th>
      <th><%= model_class.human_attribute_name(:transfers_in) %></th>
      <th><%= model_class.human_attribute_name(:news) %></th>
      <th><%= model_class.human_attribute_name(:original_cost) %></th>
      <th><%= model_class.human_attribute_name(:event_points) %></th>
      <th><%= model_class.human_attribute_name(:news_return) %></th>
      <th><%= model_class.human_attribute_name(:next_fixture) %></th>
      <th><%= model_class.human_attribute_name(:transfers_in_event) %></th>
      <th><%= model_class.human_attribute_name(:selected_by) %></th>
      <th><%= model_class.human_attribute_name(:team_id) %></th>
      <th><%= model_class.human_attribute_name(:photo_mobile_url) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= link_to player.id, player_path(player) %></td>
        <td><%= player.first_name %></td>
        <td><%= player.second_name %></td>
        <td><%= player.elementid %></td>
        <td><%= player.transfers_out %></td>
        <td><%= player.code %></td>
        <td><%= player.event_total %></td>
        <td><%= player.last_season_points %></td>
        <td><%= player.squad_number %></td>
        <td><%= player.transfers_balance %></td>
        <td><%= player.news_updated %></td>
        <td><%= player.news_added %></td>
        <td><%= player.event_cost %></td>
        <td><%= player.web_name %></td>
        <td><%= player.in_dreamteam %></td>
        <td><%= player.team_code %></td>
        <td><%= player.shirt_image_url %></td>
        <td><%= player.transfers_out_event %></td>
        <td><%= player.element_type_id %></td>
        <td><%= player.max_cost %></td>
        <td><%= player.selected %></td>
        <td><%= player.min_cost %></td>
        <td><%= player.total_points %></td>
        <td><%= player.type_name %></td>
        <td><%= player.team_name %></td>
        <td><%= player.status %></td>
        <td><%= player.added %></td>
        <td><%= player.form %></td>
        <td><%= player.shirt_mobile_image_url %></td>
        <td><%= player.current_fixture %></td>
        <td><%= player.now_cost %></td>
        <td><%= player.points_per_game %></td>
        <td><%= player.transfers_in %></td>
        <td><%= player.news %></td>
        <td><%= player.original_cost %></td>
        <td><%= player.event_points %></td>
        <td><%= player.news_return %></td>
        <td><%= player.next_fixture %></td>
        <td><%= player.transfers_in_event %></td>
        <td><%= player.selected_by %></td>
        <td><%= player.team_id %></td>
        <td><%= player.photo_mobile_url %></td>
        <td><%=l player.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_player_path(player), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      player_path(player),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_player_path,
            :class => 'btn btn-primary' %>

app/views/players/listjson.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:second_name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= link_to player.id, player_path(player) %></td>
        <td><%= player.first_name %></td>
        <td><%= player.last_name %></td>
        <td><%=l player.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_player_path(player), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      player_path(player),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_player_path,
            :class => 'btn btn-primary' %>

app/views/players/new.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>